version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: rygneco-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: rygneco
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rygneco-network

  # Backend API
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    container_name: rygneco-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/rygneco?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - rygneco-network

  # Frontend React App
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    container_name: rygneco-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - rygneco-network

volumes:
  mongodb_data:

networks:
  rygneco-network:
    driver: bridge