name: Build & Package

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Frontend Pipeline", "Backend Pipeline"]
    types:
      - completed

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/backend/Dockerfile
        target: production
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/rygneco-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/rygneco-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/frontend/Dockerfile
        target: production
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/rygneco-frontend:latest
          ${{ secrets.DOCKER_USERNAME }}/rygneco-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/rygneco-backend:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true
