name: Frontend Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allows manual triggering

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Create ESLint config
      run: |
        cd frontend
        echo 'module.exports = {
          parser: "@typescript-eslint/parser",
          extends: [
            "eslint:recommended",
            "plugin:@typescript-eslint/recommended",
            "plugin:react/recommended",
            "plugin:react-hooks/recommended"
          ],
          parserOptions: { 
            ecmaVersion: 2020, 
            sourceType: "module",
            ecmaFeatures: {
              jsx: true
            }
          },
          env: { 
            browser: true,
            es6: true,
            node: true,
            jest: true
          },
          settings: {
            react: {
              version: "detect"
            }
          },
          rules: {
            "react/react-in-jsx-scope": "off"
          }
        };' > .eslintrc.js
    
    - name: Run ESLint
      run: |
        cd frontend
        npm run lint
      continue-on-error: true
    
    - name: Run Prettier check
      run: |
        cd frontend
        npx prettier --check src/
    
    - name: Run unit tests
      run: |
        cd frontend
        npm run test -- --coverage --watchAll=false
    
    - name: Build application
      run: |
        cd frontend
        npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/
